# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mwagner <mwagner@student.42wolfsburg.de>   +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/12/07 16:07:35 by mwagner           #+#    #+#              #
#    Updated: 2021/12/08 16:53:52 by mwagner          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

TEXT = "42 is for the braves" #Variables have CAPITAL LETTERS in a Makefile
TEXT2 = "42 might not be for the braves"

rule_a:
	echo $(TEXT)
rule_b: rule_a
	@echo $(TEXT2)